### ISSUE TITLE
top widget是怎么样的实现原理呀？

### ISSUE THREAD

**Issue by githubCK** [octree/Octree#4]
里面各种各样的效果，似乎很多都非常难实现，特别是动画。真心求教~

**Comment by octree** [comment]
有部分动画是开源的，可以在 GitHub 上找到，公司没打算开源的部分，肯定不能透露的

**Comment by githubCK** [comment]
我review了下animation的部分，是用ClockHandRotationKit的。思路非常巧妙啊，厉害！
